version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./certs:/certs
    - ./web:/web
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  php:
    image: php:7.4-fpm-alpine
    volumes:
    - ./web:/web
    - ./php.ini-production:/usr/local/etc/php/php.ini
